# Generated by Django 4.1.2 on 2022-10-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animesquizz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anime',
        ),
        migrations.DeleteModel(
            name='anime_genre',
        ),
        migrations.DeleteModel(
            name='contenu_question',
        ),
        migrations.DeleteModel(
            name='genre',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.DeleteModel(
            name='reponse',
        ),
    ]
